# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class C3pm < Formula
  desc ""
  homepage ""
  version "0.0.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/c3pm-labs/c3pm/releases/download/v0.0.1/c3pm_0.0.1_Darwin_x86_64.tar.gz"
    sha256 "c957d835dc1f95a302115043b9146f14e1c589d66ccb1d2a7f239ad0a9590187"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/c3pm-labs/c3pm/releases/download/v0.0.1/c3pm_0.0.1_Linux_x86_64.tar.gz"
    sha256 "6e2daaddd48ff7a617dbe8df36a348a13ea4e9c624aff0d98ff7f96d95d4c28f"
  end

  def install
    bin.install "ctpm"
  end
end
