# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class C3pm < Formula
  desc ""
  homepage ""
  version "0.2.0"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/c3pm-labs/c3pm/releases/download/v0.2.0/c3pm_0.2.0_Darwin_x86_64.tar.gz"
      sha256 "0de990418e3a63f50650f5a8dd4f4669f8c1dba10e04ab273349581c6b192fc4"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/c3pm-labs/c3pm/releases/download/v0.2.0/c3pm_0.2.0_Linux_x86_64.tar.gz"
      sha256 "dba902a18d0e2a304ceeefbc686c7f3ed22093aa2c492b597f57093a20504fe8"
    end
  end

  def install
    bin.install "ctpm"
  end
end
